import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Client from 'App/Models/Client';

export default class extends BaseSeeder {
  public async run() {
    await Client.createMany([
      {
        status: true,
        cellphone: '(11) 99336-9376',
        cnpj: '07459477000189',
        accountant: 'CONTADOR',
        nfeDirectory: 'C:/Le Store/',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'caioviniii@gmail.com',
        phone: '(11) 2554-8082',
        system: 'LESTORE',
        nfe: true,
        corporateName: 'ACAO COMERCIO DE EQUIPAMENTOS DE INFORMATICA EIRELI',
        sat: true,
        name: 'ACAO COMERCIO DE EQUIPAMENTOS DE INFORMATICA EIRELI',
      },
      {
        status: true,
        cellphone: '(11) 94700-1163',
        cnpj: '09102573000109',
        accountant: 'CONTADOR JUAN UTILIDADES',
        satDirectory: 'C:/POS/',
        clientEmail: 'alan_272011@hotmail.com',
        accountantEmail: 'teknilopes@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'JOAO GONCALVES DE ANDRADE NETO UTILIDADES',
        sat: true,
        nfe: false,
        name: 'JUAN UTILIDADES',
      },
      {
        status: true,
        cellphone: '(13) 98864-8215',
        cnpj: '18503531000162',
        accountant: 'AFIFE ASSESORIA CONTABIL',
        satDirectory: 'C:/POS/',
        accountantEmail: 'novamaia.contabilidade.fiscal@gmail.com',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'LU QIFENG - PRESENTES',
        sat: true,
        nfe: false,
        name: 'LU QIFENG - PRESENTES',
      },
      {
        status: true,
        cellphone: '(11) 96269-8543',
        cnpj: '14715661000108',
        accountant: 'TEKNILOPES',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'jhennylopes15@hotmail.com',
        accountantEmail: 'teknilopes@terra.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'M. DAS DORES LOPES DE LIMA UTILIDADES',
        sat: true,
        nfe: false,
        name: 'DORA UTILIDADE',
      },
      {
        status: true,
        cellphone: '(11) 99966-5543',
        cnpj: '67401125000102',
        accountant: 'NATALHIA - RECONTEC',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'llaurentys@yahoo.com.br',
        accountantEmail: 'natalia.recontec@gmail.com;llaurentys@yahoo.com.br',
        phone: '(11) 4796-8525',
        system: 'LESTORE',
        corporateName: 'PAZZIA BOMBONIERI E CAFE LTDA',
        sat: true,
        nfe: false,
        name: 'PAZZIA BOMBONIERI E CAFE LTDA',
      },
      {
        status: true,
        cellphone: '(11) 98529-2699',
        cnpj: '04430958000173',
        accountant: 'IVOLUI',
        satDirectory: 'C:/POS/',
        accountantEmail: 'ivolui@terra.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'PASTELANDIA BIAGGIO',
        sat: true,
        nfe: false,
        name: 'PASTELANDIA BIAGGIO - JACU PESSEGO',
      },
      {
        status: true,
        cellphone: '(11) 99336-9376',
        cnpj: '32888719000105',
        accountant: 'CIDENI',
        satDirectory: 'C:/POS/',
        clientEmail: 'zipperxml@gmail.com',
        accountantEmail: 'cideni@carreracontabil.com.br',
        phone: '(11) 3987-1455',
        system: 'MOBILITY',
        corporateName: 'FACO SUSHI BAR E RESTAURANTE LTDA',
        sat: true,
        nfe: false,
        name: 'NAKAJYMA SUSHI FACÓ',
      },
      {
        status: true,
        cellphone: '(11) 99598-4682',
        cnpj: '43187952000179',
        accountant: 'AVS',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'mikaellensantos835@gmail.com',
        accountantEmail: 'avs@ksassessoria.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'M. PINGO DE OURO',
        sat: true,
        nfe: false,
        name: 'MERCADO PINGO DE OURO',
      },
      {
        status: true,
        cellphone: '(11) 96018-2444',
        cnpj: '21171776000114',
        satDirectory: 'C:/POS/',
        clientEmail: 'org.ecom150@gmail.com',
        accountantEmail: 'org.ecom150@gmail.com',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'TOCA DO ACARAJE',
        sat: true,
        nfe: false,
        name: 'TOCA DO ACARAJE',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '35779228000106',
        accountant: 'AMIGOSDOACOUGUE',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'marilenesantos61@gmail.com',
        accountantEmail: 'amigosdoacougue@gmail.com',
        phone: '(11) 2554-8082',
        system: 'LESTORE',
        corporateName: 'AURIA CAROLINE ALVES TEIXEIRA ACOUGUE LTDA',
        sat: true,
        nfe: false,
        name: 'AURIA CAROLINE ALVES TEIXEIRA ACOUGUE LTDA',
      },
      {
        status: true,
        cellphone: '(11) 96392-7283',
        cnpj: '18861313000108',
        accountant: 'ARI',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'ari.bmcontabilidade@terra.com.br',
        phone: '(11) 2055-6867',
        system: 'LESTORE',
        corporateName: 'RICARDO ARAUJO VIEIRA SANTOS ACOUGUE',
        sat: true,
        nfe: false,
        name: 'BOI MANSO',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '27147998000108',
        accountant: 'ARI',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'ari.bmcontabilidade@terra.com.br',
        system: 'LESTORE',
        corporateName: 'ANALICIO RODRIGUES EVANGELISTA',
        sat: true,
        nfe: false,
        name: 'DOCES & BEBIDAS CENTENARIO',
      },
      {
        status: true,
        cellphone: '(11) 95988-9699',
        cnpj: '54428628000111',
        accountant: 'ESCENTER',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        clientEmail: 'celia_enzo@hotmail.com',
        accountantEmail: 'escenter@terra.com.br',
        phone: '(11) 2554-8082',
        system: 'ACSN',
        corporateName: 'POPOTINHO COMERCIO DE CONFECCOES E ACESSORIOS LTDA',
        sat: true,
        nfe: false,
        name: 'POPOTINHO COMERCIO DE CONFECCOES E ACESSORIOS LTDA',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '36579992000109',
        accountant: 'ARI.BMCONTABILIDADE@TERRA.COM.BR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'daltoncardoso.daltoncardoso@hotmail.com',
        accountantEmail: 'ari.bmcontabilidade@terra.com.br',
        phone: '(11) 5656-5511',
        system: 'LESTORE',
        corporateName: 'MARCOS DE OLIVEIRA CARDOSO',
        sat: true,
        nfe: false,
        name: 'RACOES E OVOS CARDOSO',
      },
      {
        status: true,
        cellphone: '(11) 98557-8995',
        cnpj: '26632733000132',
        accountant: 'VALDEMIR CONTABIL',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'mariza.almeidacalcados@uol.com.br',
        accountantEmail: 'valdemir@vccontabilidade.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'MARIZA DE ALMEIDA DOS SANTOS CALCADOS E COFECCOES',
        sat: true,
        nfe: false,
        name: 'MARIZA DE ALMEIDA DOS SANTOS CALCADOS E COFECCOES',
      },
      {
        status: true,
        cellphone: '(11) 97802-6374',
        cnpj: '24601398000180',
        accountant: 'CARLOS',
        satDirectory: 'C:/POS/',
        accountantEmail: 'passosfrancaf@uol.com.br ',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'ZHAO RULIN',
        sat: true,
        nfe: false,
        name: 'ZHAO RULIN',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '12082374000182',
        accountant: 'CONTADOR',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'johniba@terra.com.br',
        system: 'MOBILITY',
        corporateName: 'J. P. DOS SANTOS MINI MERCADO',
        sat: true,
        nfe: false,
        name: 'MERCADO DA FAZENDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '02858642000151',
        accountant: 'MORGANA',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'fiscal@ptzcontabil.com.br',
        system: 'LESTORE',
        corporateName: 'DAMORE PERFUMARIA',
        sat: true,
        nfe: false,
        name: 'M DO SOCORRO VIEIRA PERFUMARIA',
      },
      {
        status: true,
        cellphone: '(11) 95441-5959',
        cnpj: '65404444000138',
        accountant: 'JC ACESSORIA',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'jc.acessoria.contabil@hotmail.com',
        accountantEmail: 'cezabreu@terra.com.br',
        phone: '(00) 0000-0000',
        system: 'SAURUS',
        corporateName: 'FEIJOADA CHIC',
        sat: true,
        nfe: false,
        name: 'ARIANE FEIJOADA CHIC',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '09525655000158',
        accountant: 'CARLOS ',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br;flavia.contabilpassos@gmail.com',
        system: 'LESTORE',
        corporateName: 'BIJUTERIA LILIANE',
        sat: true,
        nfe: false,
        name: 'WU BINGXIONG',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '50771104000178',
        accountant: 'ELIZABHET',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        accountantEmail: 'elizabeth.fiscal@jotacontabilidade.com.br',
        system: 'ACSN',
        corporateName: 'RECAULESTE DE PNEUS',
        sat: true,
        nfe: false,
        name: 'RECAULESTE COMERCIO DE PNEUS LTDA',
      },
      {
        status: true,
        cellphone: '(11) 99966-5543',
        cnpj: '67401125000102',
        accountant: 'RECONTEC',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'llaurentys@yahoo.com.br',
        accountantEmail: 'natalia.recontec@gmail.com',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'PAZZIA BOMBONIERI E CAFE LTDA',
        sat: true,
        nfe: false,
        name: 'PAZZIA BOMBONIERI E CAFE LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '44102309000168',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        accountantEmail: 'fiscal@fatorcontabil.com.br',
        system: 'SAURUS',
        corporateName: 'BELA SIRIA LTDA',
        sat: true,
        nfe: false,
        name: 'RESTAURANTE, PIZZARIA E LANCHONETE BELA SIRIA LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '14410361000110',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'SAURUS',
        corporateName: 'COMERCIAL EMI / MARCELO KEIJI INABA',
        sat: true,
        nfe: false,
        name: 'MARCELO KEIJI INABA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '41033543000192',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'LESTORE',
        corporateName: 'POP REAL VARIEDADES',
        sat: true,
        nfe: false,
        name: 'POP REAL COMERCIO DE UTILIDADES DOMESTICAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '61211165000105',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'fiscal@orgbrasilia.com.br',
        system: 'LESTORE',
        corporateName: 'PIZZARIA E CHURRASCARIA MORAIS LTDA',
        sat: true,
        nfe: false,
        name: 'PIZZARIA E CHURRASCARIA MORAIS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '23661210000126',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: ' jlacintabilidade@outlook.com',
        system: 'LESTORE',
        corporateName: 'RMB - RESTAURANTE',
        sat: true,
        nfe: false,
        name: 'RMB - RESTAURANTE, MERCADO E BOMBONIERE EIRELI',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '67825075000182',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'SAURUS',
        corporateName: 'MITIKO AKAMINE',
        sat: true,
        nfe: false,
        name: 'MITIKO AKAMINE',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '03011417000148',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'anderson@rumarcontabilidade.com.br',
        system: 'LESTORE',
        corporateName: 'BECO MABRUCA',
        sat: true,
        nfe: false,
        name: 'BECO MABRUCA COMERCIO DE MERCADORIAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '05894193000195',
        accountant: 'CARLOS',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'LESTORE',
        corporateName: 'M L UTILIDADES DOMESTICAS ',
        sat: true,
        nfe: false,
        name: 'M L UTILIDADES DOMESTICAS LTDA',
      },
      {
        status: true,
        cellphone: '(11) 99414-6882',
        cnpj: '57962185000132',
        accountant: 'MEIRE',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'fiscal.paulistano@gmail.com',
        phone: '(11) 3941-3714',
        system: 'LESTORE',
        corporateName: 'CASA DE CARNES CAJU LTDA',
        sat: true,
        nfe: false,
        name: 'CASA DE CARNES CAJU',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '11847527000172',
        accountant: 'CONTADOR',
        satDirectory: 'C:/FOCUS 1.0x',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'fiscal@orteccontabil.com.br',
        system: 'FOCUS',
        corporateName: 'ZHU JIANGUANG',
        sat: true,
        nfe: false,
        name: 'ZHU JIANGUANG',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '02816614000171',
        accountant: 'WANDERSON',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'wanderson.contabilpassos@gmail.com',
        system: 'SAURUS',
        corporateName: 'CASTELO REAL ',
        sat: true,
        nfe: false,
        name: 'CASTELO REAL UTILIDADES DOMESTICAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '16654967000127',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'LESTORE',
        corporateName: 'UNIVERSO DO 1 99 ',
        sat: true,
        nfe: false,
        name: 'UNIVERSO DO 1 99 COMERCIO DE UTILIDADES DOMESTICA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '04431436000196',
        accountant: 'CARLINHOS',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'flavia.contabilpassos@gmail.com',
        system: 'LESTORE',
        corporateName: 'J ACACIO COMERCIO ',
        sat: true,
        nfe: false,
        name: 'J ACACIO COMERCIO DE UTILIDADES DOMESTICAS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '12056991000103',
        accountant: 'CONTADOR',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'flavia.contabilpassos@gmail.com ',
        system: 'MOBILITY',
        corporateName: 'SUPER LOJAO DO REAL',
        sat: true,
        nfe: false,
        name: 'SUPER LOJAO DO REAL LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '18503531000162',
        accountant: 'CONTADOR',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'novamaia.contabilidade.fiscal@gmail.com',
        system: 'MOBILITY',
        corporateName: 'MODA MISS',
        sat: true,
        nfe: false,
        name: '>LU QIFENG PRESENTES',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '16479703000184',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'focallconsult@gmail.com',
        system: 'SAURUS',
        corporateName: 'MERCADO FENIX ',
        sat: true,
        nfe: false,
        name: 'DENISE PONTES DOS SANTOS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '15070523000181',
        accountant: 'CONTADOR',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'fiscal@contabilidadeimperial.com.br',
        system: 'MOBILITY',
        corporateName: 'ADEGA TRES IRMAOS',
        sat: true,
        nfe: false,
        name: 'LUCIANA PEREIRA DE SANTANA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '00627192000160',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'SAURUS',
        corporateName: 'BAZAR E PERFUMARIA AKINA',
        sat: true,
        nfe: false,
        name: 'BAZAR E PERFUMARIA AKINA LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '05476992000141',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'amigosdoacougue@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'CASA DE CARNES BOI DA ESTACAO ',
        sat: true,
        name: 'CASA DE CARNES BOI DA ESTACAO LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '12056991000103',
        accountant: 'CARLINHOS',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'MOBILITY',
        corporateName: 'SUPER LOJAO DO REAL LTDA',
        sat: true,
        nfe: false,
        name: 'SUPER LOJAO DO REAL LTDA',
      },
      {
        status: true,
        cellphone: '(00) 00000-0000',
        cnpj: '07626832000167',
        accountant: 'FERNADA ESCRITORIO',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'amigosdoacougue@gmail.com',
        phone: '(11) 4609-1915',
        system: 'LESTORE',
        corporateName: 'CASA DE CARNE BOI DA ESTAÇÃO - CENTRO  LTDA',
        sat: true,
        nfe: false,
        name: 'CASA DE CARNE BOI DA ESTAÇÃO - CENTRO LTDA',
      },
      {
        status: true,
        cnpj: '45573524000100',
        accountant: 'CONTADOR IMS VISAO',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'katiacontabil@lmsvisao.com.br',
        cellphone: '(11) 98809-0161',
        phone: '(00) 00000-0000',
        system: 'MOBILITY',
        corporateName: 'MOTEL ESTANCIA CANTAREIRA LTDA',
        sat: true,
        nfe: false,
        name: 'MOTEL ESTANCIA CANTAREIRA LTDA',
      },
      {
        status: true,
        cellphone: '(11) 98398-2864',
        cnpj: '01917366000192',
        accountant: 'CRISTINA',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'ferragenstakayanagui@gmail.com',
        accountantEmail: 'mcasconfiscal@gmail.com',
        phone: '(11) 2919-4542',
        system: 'LESTORE',
        corporateName: 'YAMAMOTO FERRAGENS & CIA LTDA',
        sat: true,
        nfe: false,
        name: 'YAMAMOTO FERRAGENS & CIA LTDA',
      },
      {
        status: true,
        cellphone: '(11) 97466-3101',
        cnpj: '15371666000123',
        accountant: 'ORTEC',
        satDirectory: 'C:/FOCUS 1.0x',
        accountantEmail: 'contato@orteccontabil.com.br ',
        phone: '(11) 4799-0399',
        system: 'FOCUS',
        corporateName: 'WU MIAORU BIJUTERIAS',
        sat: true,
        nfe: false,
        name: 'WU MIAORU BIJUTERIAS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '05823184000103',
        accountant: 'IDEIA',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'ideia.acontabil@hotmail.com',
        system: 'ACSN',
        corporateName: 'RAIMUNDO DE PAIVA BENTO MERCEARIA E BAZAR',
        sat: true,
        nfe: false,
        name: 'RAIMUNDO DE PAIVA BENTO MERCEARIA E BAZAR',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '20369017000128',
        accountant: 'PEDROSO',
        satDirectory: 'C:/POS/',
        accountantEmail: 'pedrosocontab@terra.com.br',
        phone: '(11) 4636-4387',
        system: 'MOBILITY',
        corporateName: 'ANDRE LUIZ FONSECA OLIVEIRA',
        sat: true,
        nfe: false,
        name: 'ANDRE LUIZ FONSECA OLIVEIRA',
      },
      {
        status: true,
        cellphone: '(11) 95420-2438',
        cnpj: '12275704000156',
        accountant: 'CAIQUE',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'jcorg@terra.com.br',
        accountantEmail: 'caique.m.s@outlook.com',
        phone: '(11) 5562-4451',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'NILSON DOS SANTOS BARBOSA - ACOUGUE',
        sat: true,
        name: 'CASA DE CARNES BOM VIZINHO',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '33855273000177',
        accountant: 'VALDEMIR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'raphaelpratass@gmail.com',
        accountantEmail: 'valdemir@vccontabilidade.com.br',
        phone: '(11) 9474-2844',
        system: 'LESTORE',
        corporateName: 'RAFAEL GOMES DOS SANTOS',
        sat: true,
        nfe: false,
        name: 'RAPHAEL PRATAS',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '34700003000150',
        accountant: 'MARCELINO',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'vivianesimoesv@hotmail.com',
        accountantEmail: 'fiscal02@contabilidademcelino.com.br',
        phone: '(11) 97508-6072',
        system: 'LESTORE',
        corporateName: 'V.F.S. DA SILVA - PERFUMARIA',
        sat: true,
        nfe: false,
        name: 'V.F.S. DA SILVA - PERFUMARIA',
      },
      {
        status: true,
        cellphone: '(11) 93445-0115',
        cnpj: '10691257000190',
        accountant: 'CAIO',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'controleunico@terra.com.br',
        accountantEmail: 'caio@vccontabilidade.com.br',
        phone: '(11) 4201-1536',
        system: 'LESTORE',
        corporateName: 'FLORES PRA VOCE - COMERCIO LTDA',
        sat: true,
        nfe: false,
        name: 'FLORES PRA VOCE',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '42.795.445/0001-55',
        accountant: 'CONTADOR',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'CONVENIENCIA VOVO RAPHAEL',
        sat: true,
        nfe: false,
        name: 'LUCAS MESSA RODRIGUES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98090-6204',
        cnpj: '07626832000167',
        accountant: 'JOSE',
        satDirectory: 'C:/FOCUS 1.0x',
        accountantEmail: 'jose.inhuma@gmail.com',
        system: 'FOCUS',
        corporateName: 'CENTER CARNES AMIGOS DO ACOUGUE',
        sat: true,
        nfe: false,
        name: 'CENTER CARNES AMIGOS DO ACOUGUE LTDA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96698-2802',
        cnpj: ' 12275704000237',
        accountant: 'ERIC',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'ericoliveira@provisaocontabil.com.br',
        system: 'LESTORE',
        corporateName: 'NILSON DOS SANTOS BARBOSA - ACOUGUE',
        sat: true,
        nfe: false,
        name: 'CASA DE CARNE BOM VIZINHO II',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 94573-7958',
        cnpj: '31728970000131',
        accountant: 'EDINALDO',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'edinaldo.oliveira@eclcont.com.br',
        system: 'LESTORE',
        corporateName: ' NACLE & FERREIRA ALIMENTACAO LTDA',
        sat: true,
        nfe: false,
        name: 'DON BIBO',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 94973-3076',
        cnpj: '03718218000174',
        accountant: 'FORÇA NOVA CONTABIL',
        satDirectory: 'C:/POS/',
        accountantEmail: 'forcanovacontabil@terra.com.b',
        system: 'MOBILITY',
        corporateName: 'LANCHONETE BARRA FUNDA ',
        sat: true,
        nfe: false,
        name: 'LANCHONETE BARRA FUNDA LTDA',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '01392237000128',
        accountant: 'ROTA',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        clientEmail: 'anapaula_antonini@hotmaol.com',
        accountantEmail: 'rotacontabil@uol.com.br',
        phone: '(11) 3078-7938',
        system: 'ACSN',
        corporateName: 'GABRIELA COMERCIO DE CONFECCOES LIMITADA',
        sat: true,
        nfe: false,
        name: 'GABRIELA COMERCIO DE CONFECCOES LIMITADA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98856-1283',
        cnpj: '27276171000102',
        accountant: 'ADVANCON',
        satDirectory: 'C:/FOCUS 1.0x',
        accountantEmail: 'contabilidade@advancon.com.br',
        system: 'FOCUS',
        corporateName: 'JPV LINGERIE LTDA',
        sat: true,
        nfe: false,
        name: 'TODA BELLA LINGERIE',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '11223729000143',
        accountant: 'CARLOS',
        satDirectory: 'C:/FOCUS 1.0x',
        clientEmail: 'passosfrancaf@uol.com.br ',
        accountantEmail: 'passosfrancaf@uol.com.br ',
        system: 'FOCUS',
        corporateName: ' TTANAKA & MELO COMERCIO DE UTILIDADES DOMESTICAS E MERCEARIA LTDA',
        sat: true,
        nfe: false,
        name: 'TANAKA & MELO COMERCIO DE UTILIDADES DOMESTICAS E MERCEARIA LTDA',
      },
      {
        status: true,
        cellphone: '(11) 93336-5505',
        cnpj: '26743117000310',
        accountant: 'VENDAS',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'vendas@bateriasv8.com.br',
        accountantEmail: 'vendas@bateriasv8.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'BATERIAS V8 - FILIAL 02 - GUARULHOS - SP',
        sat: true,
        nfe: false,
        name: 'BATERIAS V8 - FILIAL 02 - GUARULHOS - SP',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95430-2579',
        cnpj: '52131844000175',
        accountant: 'JULIANA',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'juliana@chirayama.com.br',
        system: 'LESTORE',
        corporateName: 'FLORICULTURA ELITE LTDA',
        sat: true,
        nfe: false,
        name: 'FLORICULTURA ELITE',
      },
      {
        status: true,
        cellphone: '(00) 00000-0000',
        cnpj: '67401125000102',
        accountant: 'CONTADOR RECONTEC',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'natalia.recontec@gmail.com, llaurentys@yahoo.com.br',
        phone: '(11) 4796-8525',
        system: 'LESTORE',
        corporateName: 'PAZZIA BOMBONIERI E CAFE LTDA',
        sat: true,
        nfe: false,
        name: 'PAZZIA BOMBONIERI E CAFE LTDA',
      },
      {
        status: true,
        cellphone: '(11) 97656-0583',
        cnpj: '05894193000195',
        accountant: 'CARLINHOS PASSOS CONTABILIDADE',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'M.L. UTILIDADES DOMESTICAS LTDA',
        sat: true,
        nfe: false,
        name: 'M.L. UTILIDADES DOMESTICAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98104-4604',
        cnpj: '62724067000126',
        accountant: 'ANA',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        accountantEmail: 'ana.contabilderli@terra.com.br',
        system: 'ACSN',
        corporateName: "MAGAZINE'S IRMAOS NUNES LTDA",
        sat: true,
        nfe: false,
        name: "MAGAZINE'S IRMAOS NUNES",
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98976-3603',
        cnpj: '36280657000105',
        accountant: 'TEKNI LOPES',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'teknilopes@uol.com.br',
        system: 'LESTORE',
        corporateName: 'JL DE LIMA LEMOS UTILIDADES',
        sat: true,
        nfe: false,
        name: 'JM UTILIDADES',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '46569541000136',
        accountant: 'CCONT',
        satDirectory: 'C:/Le Store/',
        clientEmail: ' susana200716@hotmail.com',
        accountantEmail: 'contabilidadeccont@gmail.com',
        system: 'LESTORE',
        corporateName: 'AMIGOS DO ZE LTDA',
        sat: true,
        nfe: false,
        name: 'AMIGOS DO ZE LTDA',
      },
      {
        status: true,
        cellphone: '(11) 97180-7390',
        cnpj: '07096924000182',
        accountant: 'DAIANE THAMARI',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'daiane@thamari.com.br',
        phone: '(00) 0000-0000',
        system: 'SAURUS',
        corporateName: 'ATELIER LACOS E FITAS LTDA',
        sat: true,
        nfe: false,
        name: 'ATELIER LACOS E FITAS LTDA',
      },
      {
        status: true,
        cellphone: '(11) 93200-8290',
        phone: '(00) 0000-0000',
        cnpj: '47026414000153',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'CASA DE CARNES IRENE - EIRELI',
        sat: true,
        nfe: false,
        name: 'CASA DE CARNES IRENE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 99665-1082',
        cnpj: '05259459000128',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'GOMES NOGUEIRA -MATERIAL DE CONSTRUÇÃO',
        sat: true,
        nfe: false,
        name: 'GOMES NOGUEIRA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96483-7315',
        cnpj: '21261940000104',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'MARCIO ROCHA CORDEIRO 21490567801',
        sat: true,
        nfe: false,
        name: 'MARCIO ROCHA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '31440773000112',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'JOSE DOMINGOS DOS SANTOS - MERCADINHO',
        sat: true,
        nfe: false,
        name: 'JOSE DOMINGOS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97744-7738',
        cnpj: '24623151000164',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'pandababy57@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'KARINA MATOS SILVA - ME',
        sat: true,
        nfe: false,
        name: 'PANDA BABY',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98587-5170',
        cnpj: '30800556000123',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'REALCE COMERCIO DE TINTAS TOQUE FINAL LT',
        sat: true,
        nfe: false,
        name: 'TOQUE FINAL',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '13453173000107',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'MERCADINHO VICTOR LINS',
        sat: true,
        nfe: false,
        name: 'MERCADINHO VICTOR LINS',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '32677519000103',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        phone: '(11) 2764-7090',
        system: 'LESTORE',
        corporateName: 'LAURISLEIA APARECIDA ALVES DE ALMEIDA SI',
        sat: true,
        nfe: false,
        name: 'IMPACTO GAS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97066-0520',
        cnpj: '44342997000133',
        accountant: 'JLA CONTABIL',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'jlacontabilidade@outlook.com',
        system: 'LESTORE',
        corporateName: 'PANIFICADORA FAMILIA SILVA LTDA',
        sat: true,
        nfe: false,
        name: 'PANIFICADORA FAMILIA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 99294-5394',
        cnpj: '13040428000100',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'USINAGEM TORELLI LTDA',
        sat: true,
        nfe: false,
        name: 'USINAGEM TORELLI',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95459-2649',
        cnpj: '34984311000154',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'TABADEGA DO JAPA',
        sat: true,
        nfe: false,
        name: 'TABADEGA DO JAPA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '29657654000174',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'AVANDRO SANTOS DOS ANJOS 02324078511',
        sat: true,
        nfe: false,
        name: 'AVANDRO',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95922-7592',
        cnpj: '06104322000167',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'MOBILITY',
        corporateName: 'MIK ESFIHAS LIMA LTDA - ME',
        sat: true,
        nfe: false,
        name: 'MIK ESFIHAS LIMA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 94752-9542',
        cnpj: '27147998000108',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'MOBILITY',
        corporateName: 'ANALICIO RODRIGUES EVANGELISTA',
        sat: true,
        nfe: false,
        name: 'GELADAO MIX',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95916-4412',
        cnpj: '40632657000196',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'MOBILITY',
        corporateName: 'AGUA FRIA SUSHI BAR E RESTAURANTE LTDA',
        sat: true,
        nfe: false,
        name: 'AGUA FRIA SUSHI',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98602-5704',
        cnpj: '13237010000197',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'SAURUS',
        corporateName: 'BAR DECIO ROCK BAR LTDA - ME',
        sat: true,
        nfe: false,
        name: 'ROCK BAR',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 94946-4550',
        cnpj: '33149054000172',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'SAURUS',
        corporateName: 'MARIA NEUZENI RODRIGUES DA SILVA',
        sat: true,
        nfe: false,
        name: 'HL MODAS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '07.598.555/0001-26',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'SAURUS',
        corporateName: 'POLINEO PISOS COMERCIO DE PRODUTOS',
        sat: true,
        nfe: false,
        name: 'POLINEO PISOS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96739-3650',
        cnpj: '09127621000105',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'SAURUS',
        corporateName: 'POMPEIA - PIZZARIA DELIVERY LTDA',
        sat: true,
        nfe: false,
        name: 'POMPEIA - PIZZARIA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '33646085000139',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'AMIGOS BURGUER LTDA',
        sat: true,
        nfe: false,
        name: 'DOG & BURGUER DO CLEBAO',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '04324459000100',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'R.I.K.A COMERCIO DE MATERIAIS PARA CONST',
        sat: true,
        nfe: false,
        name: 'R.I.K.A COMERCIO DE MATERIAIS PARA CONST',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95926-5156',
        cnpj: '07910674000172',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'EDNILSON SOUZA AGUIAR - PIZZARIA - ME',
        sat: true,
        nfe: false,
        name: 'FANCIULA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96175-7970',
        cnpj: '43732631000108',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'TOWER CAFE, COMERCIO E EVENTOS LIMITADA',
        sat: true,
        nfe: false,
        name: 'TOWER CAFE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97566-2309',
        cnpj: '31275836000122',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'BEATRIZ ALICE FILHA DOS SANTOS 846222708',
        sat: true,
        nfe: false,
        name: 'RIZZA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '46190563000190',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'ASSIS HORTIFRUTI LTDA',
        sat: true,
        nfe: false,
        name: 'ASSIS HORTIFRUTI LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '05051490603',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        corporateName: 'ADENILSON GONCALVES',
        sat: true,
        nfe: false,
        name: 'DENILSON LANCHONETE',
      },
      {
        status: true,
        cellphone: '(11) 95367-4178',
        cnpj: '55920664000160',
        accountant: 'VALTER',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'ovjcontabil@gmail.com',
        accountantEmail: 'ovjcontabil@gmail.com',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: "KADILSU'S LANCHONETE LTDA",
        sat: true,
        nfe: false,
        name: "KADILSU'S LANCHONETE LTDA",
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97370-7205',
        cnpj: '11327212000102',
        accountant: 'MARCO',
        satDirectory: 'C:/POS/',
        accountantEmail: 'marco@liberty.cnt.br',
        system: 'MOBILITY',
        corporateName: 'K A B DE ANDRADE GELATERIA',
        sat: true,
        nfe: false,
        name: 'PE DE ACAI',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '02799142000196',
        satDirectory: 'C:/POS/',
        accountantEmail: 'adm.ack@acksaitocontabilidade.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'MARIA MIEKO KAWAZOI',
        sat: true,
        nfe: false,
        name: 'MARIA MIEKO KAWAZOI',
      },
      {
        status: true,
        cellphone: '(11) 93763-8386',
        cnpj: '17493738000130',
        accountant: 'AFIFE ASSESORIA CONTABIL',
        satDirectory: 'C:/POS/',
        accountantEmail: 'daiane@afifecontabil.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'ANTONIA MARIA DE OLIVEIRA - ACOUGUE - ME',
        sat: true,
        nfe: false,
        name: 'ANTONIA MARIA DE OLIVEIRA - ACOUGUE - ME',
      },
      {
        status: true,
        cellphone: '(11) 98321-7160',
        cnpj: '30619280000262',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'reis.cleber@hotmail.com',
        accountantEmail: 'nailsonvl@hotmail.com',
        phone: '(11) 2023-1379',
        system: 'LESTORE',
        corporateName: 'RINKAI SUSHI LTDA',
        sat: true,
        nfe: false,
        name: 'RINKAI SUSHI LTDA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96317-8466',
        cnpj: '66745654000152',
        accountant: 'DEBORA',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'deboraorfincontabilidade@hotmail.com',
        system: 'LESTORE',
        corporateName: 'MULTI FORMAS MODULADOS LTDA',
        sat: true,
        nfe: false,
        name: 'MULTI FORMAS MODULADOS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '05993047000117',
        satDirectory: 'C:/POS/',
        clientEmail: 'imperialfiscal@hotmail.com',
        accountantEmail: 'fiscal@contabilidadeimperial.com.br; imperialfiscal@hotmail.com',
        system: 'MOBILITY',
        corporateName: 'LUCIANA PEREIRA DE SANTANA',
        sat: true,
        nfe: false,
        name: 'ADEGA TRES IRMAOS (ANALICIO)',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96825-6791',
        cnpj: '14715661000299',
        accountant: 'LOPES',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'teknilopes@uol.com.br',
        system: 'LESTORE',
        corporateName: 'M. DAS DORES LOPES DE LIMA UTILIDADES',
        sat: true,
        nfe: false,
        name: 'M. DAS DORES LOPES DE LIMA UTILIDADES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95931-2980',
        cnpj: '42492481000140',
        accountant: 'FISCAL',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'fiscal@contabilidadeimperial.com.br',
        system: 'LESTORE',
        corporateName: 'ADEMY RODRIGUES DOS SANTOS',
        sat: true,
        nfe: false,
        name: 'ADEMY RODRIGUES DOS SANTOS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95300-5763',
        cnpj: '16922087000194',
        accountant: 'ANDERSON',
        satDirectory: 'C:/FOCUS 1.0x',
        accountantEmail: 'anderson@rumarcontabilidade.com.br',
        system: 'FOCUS',
        corporateName: 'M. A. SIQUEIRA',
        sat: true,
        nfe: false,
        name: 'BECO',
      },
      {
        status: true,
        cellphone: '(11) 93906-3877',
        cnpj: '60519402000129',
        accountant: 'FC.OLGA.MAKOTOENDO',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        clientEmail: 'mogibertiogacenter',
        accountantEmail: 'fc.olga.makotoendo@gmail.com',
        phone: '(00) 0000-0000',
        system: 'ACSN',
        corporateName: 'MOGI BERTIOGA CENTER MATERIAIS PARA CONSTRUCAO LT',
        sat: true,
        nfe: false,
        name: 'MOGI BERTIOGA CENTER MATERIAIS PARA CONSTRUCAO LT',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97797-2570',
        cnpj: '03175139000164',
        accountant: 'CONFORT',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'confort@hotmail.com',
        system: 'LESTORE',
        corporateName: 'FRANCISCO GUALBERTO DA SILVA - CONFEITARIA',
        sat: true,
        nfe: false,
        name: 'FRANCISCO GUALBERTO DA SILVA - CONFEITARIA',
      },
      {
        status: true,
        cellphone: '(11) 99292-8167',
        cnpj: '07910674000172',
        accountant: 'PASSOS',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'passosfrancaf@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'EDINILSON SOUZA AGUIAR PIZZARIA',
        sat: true,
        nfe: false,
        name: 'EDINILSON SOUZA AGUIAR PIZZARIA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95270-5131',
        cnpj: '36423701000180',
        accountant: 'EDUARDO',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'eduardo.souza@contec.com.br',
        system: 'LESTORE',
        corporateName: 'OTICAS EMILIANO LTDA',
        sat: true,
        nfe: false,
        name: 'OTICAS EMILIANO',
      },
      {
        status: true,
        cellphone: '(11) 96104-9581',
        cnpj: '14047279000173',
        accountant: 'CONTADOR',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'contabilcavicchi@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'IRMAOS TORRES SACOLAO EIRELI',
        sat: true,
        nfe: false,
        name: 'IRMAOS TORRES SACOLAO EIRELI',
      },
      {
        status: true,
        cellphone: '(11) 97696-4628',
        cnpj: '07626832000167',
        accountant: 'ESCRITORIO DO AÇOUGUE',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'amigosdoacougue@gmail.com',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'CENTER CARNES AMIGOS DO ACOUGUE LTDA',
        sat: true,
        nfe: false,
        name: 'CENTER CARNES AMIGOS DO ACOUGUE LTDA',
      },
      {
        status: true,
        cellphone: '(11) 95988-9699',
        cnpj: '54428628000111',
        accountant: 'ESCENTER CONTABIL',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'escenter@terra.com.br',
        phone: '(00) 0000-0000',
        system: 'ACSN',
        corporateName: 'POPOTINHO COMERCIO DE CONFECCOES E ACESSORIOS LTDA',
        sat: true,
        nfe: false,
        name: 'POPOTINHO COMERCIO DE CONFECCOES E ACESSORIOS LTDA',
      },
      {
        status: true,
        cellphone: '(11) 96104-9581',
        cnpj: '07341994000159',
        accountant: 'CONTABILCAVICCHI',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'contabilcavicchi@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'MOBILITY',
        corporateName: 'SACOLAO TORRES & ANDRADE EIRELI',
        sat: true,
        nfe: false,
        name: 'TORRES MERCADINHO',
      },
      {
        status: true,
        cellphone: '(11) 98090-6204',
        phone: '(00) 0000-0000',
        cnpj: '06203862000106',
        accountant: 'JULIANA',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        accountantEmail: 'wreal_julianaferreira@hotmail.com',
        system: 'ACSN',
        corporateName: 'HERICA CRISTINA CONGA INHUMA - ACOUGUE E ROTISSERIA',
        sat: true,
        nfe: false,
        name: 'CENTER CARNES CRIS',
      },
      {
        status: true,
        cellphone: '(11) 98449-4823',
        cnpj: '05894193000195',
        accountant: 'CARLOS PASSOS ',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'passosfrancaf@gmail.com',
        accountantEmail: 'passosfrancaf@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'M.L. UTILIDADES DOMESTICAS LTDA',
        sat: true,
        nfe: false,
        name: 'M.L. UTILIDADES DOMESTICAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98508-3684',
        cnpj: '17141252000133',
        accountant: 'FERRACIOLI',
        satDirectory: 'C:/POS/',
        accountantEmail: 'fiscal05@ferracioli.com.br',
        system: 'MOBILITY',
        corporateName: 'JOSE DAMIAO FERREIRA',
        sat: true,
        nfe: false,
        name: 'JOSE DAMIAO FERREIRA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97766-5696',
        cnpj: '66679853000100',
        accountant: 'PASSOS',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'passosfrancaf@uol.com.br',
        system: 'LESTORE',
        corporateName: 'WALLACE UTILIDADES DOMESTICAS LTDA',
        sat: true,
        nfe: false,
        name: 'WALLACE UTILIDADES DOMESTICAS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(00) 00000-0000',
        cnpj: '06049821000107',
        satDirectory: 'C:/POS/',
        accountantEmail: 'gecrcsuzano@gmail.com',
        system: 'MOBILITY',
        corporateName: 'PET SHOP SARDINHA LTDA',
        sat: true,
        nfe: false,
        name: 'PET SHOP SARDINHA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '02049983000186',
        accountant: 'KAILANY',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'kailany@contabilidadeobjetivo.com.br',
        system: 'LESTORE',
        corporateName: 'AGOSTINHO & ADRIANA LTDA',
        sat: true,
        nfe: false,
        name: 'REAL JÓIAS PRATAS E FOLHADOS',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 94003-9266',
        cnpj: '18861313000108',
        accountant: 'ARI',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'ari.bmcontabilidade@terra.com.br',
        system: 'LESTORE',
        corporateName: 'RICARDO ARAUJO VIEIRA SANTOS ACOUGUE',
        sat: true,
        nfe: false,
        name: 'RICARDO ARAUJO VIEIRA SANTOS ACOUGUE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98341-3542',
        cnpj: '36306487000182',
        accountant: 'ZAIRA',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'zaira@idealcontabeis.com.br',
        system: 'LESTORE',
        corporateName: 'ICE CANDY SORVETES LTDA',
        sat: true,
        nfe: false,
        name: 'ICE CANDY SORVETES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95709-7559',
        cnpj: '31163815000204',
        accountant: 'MARCELO',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'marcelocontabilpassos@gmail.com',
        system: 'LESTORE',
        corporateName: 'R & J - CORTE E MODELAGEM LTDA',
        sat: true,
        nfe: false,
        name: 'R & J - CORTE E MODELAGEM',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 93036-5033',
        cnpj: '46346703000177',
        accountant: 'RAFAEL',
        satDirectory: 'C:/ACSN/CENTRAL/auxfis/',
        accountantEmail: 'rafael@capolavorocontabil.com.br',
        system: 'ACSN',
        corporateName: 'LOJA DE TECIDOS JUNDIAI LTDA',
        sat: true,
        nfe: false,
        name: 'LOJA DE TECIDOS JUNDIAI',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98232-1428',
        cnpj: '13146973000185',
        accountant: 'SISTER',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        accountantEmail: 'contsister@hotmail.com',
        system: 'SAURUS',
        corporateName: 'CAFETERIA ACONCHEGO LTDA',
        sat: true,
        nfe: false,
        name: 'ACONCHEGO DO CAFE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97247-5374',
        cnpj: '09174494000103',
        accountant: 'VANIA',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'vania.goes@srccontabilidade.com.br',
        system: 'LESTORE',
        corporateName: 'FREDERICO VICENTE DA SILVA',
        sat: true,
        nfe: false,
        name: 'MARI DOCES',
      },
      {
        status: true,
        cellphone: '(11) 99292-8167',
        cnpj: '00627192000160',
        accountant: 'PASSOS',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        accountantEmail: 'flavia.contabilpassos@gmail.com',
        phone: '(00) 0000-0000',
        system: 'SAURUS',
        corporateName: 'BAZAR E PERFUMARIA AKINA LTDA',
        sat: true,
        nfe: false,
        name: 'BAZAR E PERFUMARIA AKINA LTDA',
      },
      {
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '17493738000130',
        accountant: 'VALMIR',
        satDirectory: 'C:/POS/',
        accountantEmail: 'valmir.cardozo@afifecontabil.com',
        phone: '(11) 4881-5996',
        system: 'MOBILITY',
        corporateName: 'ANTONIA MARIA DE OLIVEIRA - ACOUGUE',
        sat: true,
        nfe: false,
        name: 'CASA DE CARNES MASTER BOI',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98516-2164',
        cnpj: '35591956000190',
        accountant: 'STILO CONTABIL',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'stillocontabilidade@terra.com.br',
        system: 'LESTORE',
        corporateName: 'ESSENCIAL BABY EIRELI',
        sat: true,
        nfe: false,
        name: 'ESSENCIAL BABY EIRELI',
      },
      {
        status: true,
        cellphone: '(11) 95926-5156',
        cnpj: '07910674000172',
        accountant: 'PASSOS',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'flavia.contabilpassos@gmail.com; passosfrancaf@uol.com.br',
        phone: '(00) 0000-0000',
        system: 'LESTORE',
        corporateName: 'EDINILSON SOUZA AGUIAR - PIZZARIA',
        sat: true,
        nfe: false,
        name: 'FANCIULLA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95557-1045',
        cnpj: '31246449000168',
        accountant: 'MARINA',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        accountantEmail: 'marina.fiscal@columbo.com.br',
        system: 'SAURUS',
        corporateName: 'COMERCIO DE CARNES & ROTISSERIA LEBELA LTDA',
        sat: true,
        nfe: false,
        name: 'BELLO BEEF',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 97550-5388',
        cnpj: '11327212000285',
        accountant: 'MARCO ',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'pe.deacai@hotmail.com',
        accountantEmail: 'marco@liberty.cnt.br',
        system: 'LESTORE',
        corporateName: 'K A B DE ANDRADE GELATERIA',
        sat: true,
        nfe: false,
        name: 'PÉ DE AÇAÍ',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '10289459000100',
        accountant: 'NOVA LESTE ARLETE',
        satDirectory: 'C:/POS/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'novalestearlete@uol.com.br',
        system: 'MOBILITY',
        corporateName: ' LANCHONETE E CASA DO NORTE CAMBUCI LTDA',
        sat: true,
        nfe: false,
        name: 'RESTAURANTE BUCHO QUEBRADO',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96608-2961',
        cnpj: '45877575000125',
        accountant: 'PELIZON ',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'pellizzon.xml@gmail.com',
        system: 'LESTORE',
        corporateName: 'TOP REAL UTILIDADES DOMESTICAS LTDA',
        sat: true,
        nfe: false,
        name: 'TOP REAL UTILIDADES DOMESTICAS LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '62185962000110',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'MMS OTICA LTDA - ME',
        sat: true,
        name: 'MMS OTICA VILA RE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96655-9307',
        cnpj: '37414663000162',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'DALZIR PEREIRA DOS SANTOS BAR E LANCHES',
        sat: true,
        name: 'DALZIR PEREIRA DOS SANTOS BAR E LANCHES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95709-4048',
        cnpj: '33010494000144',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'MINI MERCADO E COMERCIO DE PAES SEYU',
        sat: true,
        name: 'MINI MERCADO E COMERCIO DE PAES SEYU',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98659-6468',
        cnpj: '09174494000103',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'FREDERICO VICENTE DA SILVA - ME',
        sat: true,
        name: 'MARI DOCES',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '08769694000219',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'EVALDO PEREIRA SOARES',
        sat: true,
        name: 'LOJAO SOARES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 96177-3426',
        cnpj: '07734369000177',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'HENDERSON GONCALVES',
        sat: true,
        name: 'HENDERSON GONCALVES',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '10373321000195',
        accountant: 'CLIENTE DO HELIO',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'BAR DO VARDEMA LTDA',
        sat: true,
        name: 'BAR DO VARDEMA LTDA',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98437-1933',
        cnpj: '04794121000103',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'RUBCLAY GONCALVES ME',
        sat: true,
        name: 'LA BOOM SORVETES',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 95222-3472',
        cnpj: '00292596000140',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'QUALITTA CAFE & RESTAURANTE LTDA',
        sat: true,
        name: 'QUALITTA CAFE',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 99598-4682',
        cnpj: '43187952000179',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'MERCADINHO E PADARIA LARUSSA LTDA',
        sat: true,
        name: 'PINGO DE OURO',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '41996639000156',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'LANCHONETE RAINHA DA JOVITA LTDA',
        sat: true,
        name: 'LANCHONETE RAINHA DA JOVITA LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '26847324000153',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'RENAN FEIJO DA SILVA 42019589818',
        sat: true,
        name: 'ADEGA GUABA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '12142459000109',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'ALINE ALICE DA SILVA FARIAS',
        sat: true,
        name: 'BAZAR CASTELO',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '34055332874',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'VITOR YOSHIO RISSO',
        sat: true,
        name: 'NOSTRO FUMO MOOCA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '38456027000166',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'E.M.D.S. DISTRIBUIDORA DE ALIMENTOS',
        sat: true,
        name: 'E.M.D.S. DISTRIBUIDORA DE ALIMENTOS',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '06097326000165',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'acaoautocom@gmail.com',
        accountantEmail: 'acaoautocom@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'GAMES E ELETRONICOS EM GERAL LTDA',
        sat: true,
        name: 'GAMES E ELETRONICOS EM GERAL LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '34730384000110',
        accountant: 'MRSOLUCAO',
        nfeDirectory: 'C:/Le Store/NFe/',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'nfe@mrsolucao.com.br',
        accountantEmail: 'nfe@mrsolucao.com.br',
        system: 'LESTORE',
        nfe: true,
        corporateName: 'DIAMANTEXTIL CONFECCOES LTDA',
        sat: true,
        name: 'DIAMANTEXTIL',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '03259225000155',
        accountant: 'AMIGOSDOACOUGUE@GMAIL.COM',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'amigosdoacougue@gmail.com',
        accountantEmail: 'amigosdoacougue@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'BOI BOM AMIGOS 2',
        sat: true,
        name: 'BOI BOM AMIGOS 2',
      },
      {
        status: true,
        cellphone: '(11) 98891-6938',
        cnpj: '32175881000178',
        accountant: 'ANA PAULA',
        satDirectory: 'C:/Saurus/Saurus PDV/',
        clientEmail: 'jozi_mel@hotmail.com',
        accountantEmail: 'anapaula@vitoriacontabilidade.com.br',
        phone: '(19) 8279-7214',
        system: 'SAURUS',
        nfe: false,
        corporateName: 'MERCADO MEL E FAMILIA - EIRELI',
        sat: true,
        name: 'MERCADO MEL E FAMILIA - EIRELI',
      },
      {
        status: true,
        cellphone: '(11) 94892-3425',
        cnpj: '45787482000100',
        accountant: 'MORGANA',
        satDirectory: 'C:/Le Store/',
        clientEmail: 'gilmar@ptzcontabil.com.br',
        accountantEmail: 'fiscal@ptzcontabil.com.br',
        phone: '(11) 2031-0204',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'VITORIA PERFUMARIA E PRESENTES LTDA',
        sat: true,
        name: 'VITORIA PERFUMARIA E PRESENTES LTDA',
      },
      {
        phone: '(00) 0000-0000',
        cellphone: '(00) 00000-0000',
        status: true,
        cnpj: '01482212000115',
        accountant: 'AÇÃO',
        satDirectory: 'C:/Le Store/',
        accountantEmail: 'caioviniii@gmail.com',
        system: 'LESTORE',
        nfe: false,
        corporateName: 'MARIA DA PAZ YAMAMOTO',
        sat: true,
        name: 'MERCADO YAMAMOTO',
      },
      {
        phone: '(00) 0000-0000',
        status: true,
        cellphone: '(11) 98090-6204',
        cnpj: '06203862000106',
        accountant: 'CONTADOR',
        nfeDirectory: 'C:/FOCUS 1.0x',
        satDirectory: 'C:/vendas',
        clientEmail: 'hericainhuma@hotmail.com',
        accountantEmail: 'wreal_julianaferreira@hotmail.com:hericainhuma@hotmail.com',
        system: 'FOCUS',
        nfe: true,
        corporateName: 'CENTER CARNES CRIS',
        sat: true,
        name: 'HERICA CRISTINA CONGA INHUMA - ACOUGUE E ROTISSERIA',
      },
    ]);
  }
}
